version: '3.8'

services:
  # --- 1. Database Service ---

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    volumes:
      - mongo_data:/data/db
      
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ujjwalsql@2500  
      MYSQL_DATABASE: Test1                
    volumes:
      - db_data:/var/lib/mysql

  # --- 2. Redis Service ---
  redis:
    image: redis:alpine
    restart: always

  # --- 3. Backend Server 1 ---
  backend_1:
    build: .
    restart: always
    environment:
      - DB_HOST=db        
      - REDIS_HOST=redis  
      - SECRET_KEY=supersecretkey
    depends_on:
      - db
      - redis

  # --- 4. Backend Server 2 (Identical Copy) ---
  backend_2:
    build: .
    restart: always
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - SECRET_KEY=supersecretkey
    depends_on:
      - db
      - redis

  # --- 5. Nginx (Entry Point) ---
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend_1
      - backend_2
volumes:
  db_data: